### admin v2 조회
GET http://localhost:8087/admin/v2/users/1
Accept: application/json

### admin v1 조회
GET http://localhost:8087/admin/v1/users/1
Accept: application/json

### 관리자 전체 조회
GET http://localhost:8087/admin/users
Accept: application/json

### admin 1개 조회
GET http://localhost:8087/admin/users/1
Accept: application/json

### 전체 조회(xml)
GET http://localhost:8087/users/
Accept: application/xml

### 영어
GET http://localhost:8087/hello-world-internationalized
Accept: application/json
Accept-Charset: utf-8
Accept-Language: en

### 프랑스
GET http://localhost:8087/hello-world-internationalized
Accept: application/json
Accept-Charset: utf-8
Accept-Language: fr

### 한국어(기본값)
GET http://localhost:8087/hello-world-internationalized
Accept: application/json
Accept-Charset: utf-8

###
### 신규데이터 생성(Valid fail)
POST http://localhost:8087/users
Content-Type: application/json

{
  "name": "N",
  "joinDate": "2020-10-08T15:10:25.249+0000"
}

### 3번 삭제
DELETE http://localhost:8087/users/3
Accept: application/json

### 3번 조회 ( 있는 경우 )
GET http://localhost:8087/users/3
Accept: application/json

### 100번 조회 ( 없는 경우 )
GET http://localhost:8087/users/100
Accept: application/json

### 전체 조회
GET http://localhost:8087/users/
Accept: application/json

###
GET http://localhost:8087/hello-world-bean
Accept: application/json

###
GET http://localhost:8087/hello-world
Accept: application/json

### 신규데이터 생성
POST http://localhost:8087/users
Content-Type: application/json

{
"name": "New User",
"joinDate": "2020-10-08T15:10:25.249+0000"
}




