server:
  port: 8087
logging:
  level:
    org.springframework: DEBUG

spring:
  messages:
    basename: messages
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
#  security:
#    user:
#      name: username
#      password: passw0rd



management:
  endpoints:
    web:
      exposure:
        include: "*"

